// electron-builder `afterPack` hook.
//
// Runs after the app is packed into the unpacked directory (win-unpacked) but BEFORE the
// NSIS installer is compiled. It records exactly the top-level files and folders that make
// up Hyperion's install footprint and writes them as an NSIS macro to build/uninstall-files.nsh.
//
// build/installer.nsh includes that macro inside `customRemoveFiles`, so the uninstaller
// (used by both manual uninstall AND auto-update) removes ONLY Hyperion's own files and then
// drops the install directory only if it is empty. Any user content placed alongside the app
// - the suggested `Mods` / `Downloads` folders, or any other folder the user created - is left
// untouched. This is what makes the "data lives inside the install dir" layout safe.
//
// Generating the list from the real packed output (instead of hand-maintaining it) keeps it
// correct across Electron upgrades: whatever Electron ships in the app root is what we remove.

const fs = require('fs')
const path = require('path')

/** Escape a filename for safe embedding in an NSIS double-quoted string. */
function escapeNsisName(name) {
  // `$` is the only character with special meaning inside NSIS strings; double it.
  // Electron's shipped filenames never contain quotes, but guard defensively anyway.
  return name.replace(/\$/g, '$$$$').replace(/"/g, '$\\"')
}

module.exports = async function afterPack(context) {
  if (context.electronPlatformName !== 'win32') return

  const appOutDir = context.appOutDir
  const entries = fs.readdirSync(appOutDir, { withFileTypes: true })

  const lines = [
    '# AUTO-GENERATED by scripts/after-pack.cjs during the build - do not edit by hand.',
    '# Lists exactly the files/folders Hyperion installs so the uninstaller removes only its',
    '# own footprint and never deletes user data (Mods, Downloads, or any other folder).',
    '!macro hyperionRemoveOwnedFiles',
  ]

  for (const entry of entries) {
    const name = escapeNsisName(entry.name)
    if (entry.isDirectory()) {
      lines.push(`  RMDir /r "$INSTDIR\\${name}"`)
    } else {
      lines.push(`  Delete "$INSTDIR\\${name}"`)
    }
  }

  lines.push('!macroend')

  const outFile = path.resolve(__dirname, '..', 'build', 'uninstall-files.nsh')
  fs.writeFileSync(outFile, lines.join('\r\n') + '\r\n', 'utf8')

  console.log(`[after-pack] Wrote uninstall manifest with ${entries.length} top-level entries -> ${outFile}`)
}
